### ISSUE TITLE
[IDEA] Error

### ISSUE THREAD

**Issue by ruslansenatorov** [SENATOROVAI/Data-Science-For-Beginners-from-scratch-SENATOROV#48]
### Feature description

zip

**Comment by ruslansenatorov** [comment]
[Archive.zip](https://github.com/user-attachments/files/17991087/Archive.zip)

**Comment by ruslansenatorov** [comment]
[Archive 2.zip](https://github.com/user-attachments/files/18022119/Archive.2.zip)

**Comment by kypena** [comment]
Спасибо
