### ISSUE TITLE
[TASK] statistics + pandas + sql

### ISSUE THREAD

**Issue by ruslansenatorov** [SENATOROVAI/Data-Science-For-Beginners-from-scratch-SENATOROV#65]
Делай только то что написано НИЖЕ:

1)предоставь скриншоты по каждому курсу что ты их завершила, сюда в комменты
https://github.com/SENATOROVAI/python-Tatiana/blob/5fb0e21218f3143f239763c54db56b3360f755a4/hw.txt#L56-L67

2)Реализуй ноутбуки у себя в кэггл
https://dfedorov.spb.ru/pandas/#1

3)Пройди курс по статистике, **каждый день предоставляй скриншот в комменты и ссылку на коммент кидай во флуд**
создать файл `math/stat/название_раздела_на_английском/имя_контеста.py`, загружать туда код из контеста 
 https://github.com/SENATOROVAI/python-Tatiana/blob/5fb0e21218f3143f239763c54db56b3360f755a4/hw.txt#L72
**загружаешь код из своего репозитория**
![изображение](https://github.com/user-attachments/assets/493b4e4a-a08f-43e6-b229-efae32c689b0)
3.1) [ДАТАСЭТ](https://github.com/SENATOROVAI/data1-pd)

![image](https://github.com/user-attachments/assets/912ce66f-865c-4c6e-b949-41fc45c2b3d9)

4)Проекты **по статистике** для резюме 
https://github.com/SENATOROVAI/data-pd-practicum
5)Экзаменационный контроль 
https://stepik.org/course/76/syllabus
https://stepik.org/course/524/syllabus
https://stepik.org/course/201739/syllabus

**Comment by ruslansenatorov** [comment]
@kypena 28.12

**Comment by kypena** [comment]
![image](https://github.com/user-attachments/assets/68389ed4-9287-4f19-aed8-2eb1b5263ab8)

**Comment by ruslansenatorov** [comment]
мы переехали https://github.com/SENATOROVAI/repo-data/issues/9
