### ISSUE TITLE
bug: C0301 Line too long with datsets

### ISSUE THREAD

**Issue by kypena** [SENATOROVAI/Data-Science-For-Beginners-from-scratch-SENATOROV#97]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://t.me/c/1937296927/3602/25534) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) or [chatGPT](https://t.me/c/1937296927/2415/23729) and didn't find any helpful information.

### Attach a full screenshot and write what did you do to fix the problem?

URL_SSR = (
    "https://raw.githubusercontent.com/yndx-handbook/data-analysis-in-social-sciences-handbook/"
    "refs/heads/main/04.%20%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD"
    "%D1%8B%D0%B5%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5/COVID-19%20SSR.csv"
)

print(df["Rating of Online Class experience"].str.title()[:5])

df_covid["Sleep"] = df_covid["Time spent on sleep"].apply(classify_sleep)
df_covid["Time spent on TV"] = df_covid["Time spent on TV"].astype("float")
print(df_sleep4["Stress busters"].str.contains("book").value_counts()[1])
df_instagram = df_i[df["Prefered social media platform"] == "Instagram"]

### Error from the terminal / Code

C0301: Line too long (101/79) (line-too-long)

### Expected behavior

Как решить ошибку  C0301 есди есть необходимость загружать датасеты и путь длинный. 
Также длинные названия в колонках датасетов и когда к ним обращаешься, то строка - длинная. При этом надо применять методы к столбцам, сравнивать, фильтровать... 

### Actual behavior

отсутствие ошибки

**Comment by ruslansenatorov** [comment]
твоя ошибку решена прими пул
